name: EnvVariable

# Triggers for the workflow
on:
  # Manual trigger using the workflow_dispatch event
  workflow_dispatch:

env:
  MONTH_OF_YEAR: December
  CURRENT_YEAR: 2023

jobs:
  holiday_status_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello

    steps:
      - name: "Provide total annual vacation days"
        if: ${{ env.CURRENT_YEAR == '2023' }}
        run: echo "$Greeting $Full_Name. As of $MONTH_OF_YEAR $CURRENT_YEAR you will have $Vacation_Days vacation days!"
        env:
          Full_Name: UdaCycle Employee
          Vacation_Days: 20

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14, 16, 18]
        platform: [ubuntu-latest, macos-latest, windows-latest]
        exclude:
          - platform: macos-latest
            node-version: 14
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Dependencies
        run: npm install

      - name: Build and Test
        run: npm run build && npm run test
        continue-on-error: true